name: "Build-Deploy"
on:
  push:
    branches:
      - main
jobs:
  Build-Deploy-Lambda:
    runs-on: ubuntu-20.04
    steps:
      - name: "Install Go"
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.17.7'

      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Run Test"
        run: go test ./...

      - name: "Build"
        run: "GOOS=linux GOARCH=amd64 go build -o whatson"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "eu-west-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Upload to S3"
        run: |
          zip whatson.zip whatson
          aws s3 cp whatson.zip s3://sab-lambda-artifact/whatson.zip

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7


      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init -input=false          

      - name: Plan Terraform
        id: plan
        continue-on-error: false
        run: |
          cd terraform
          terraform plan -input=false -out=tfplan

      - name: Apply Terraform
        if: steps.plan.outcome == 'success'
        id: apply
        continue-on-error: false
        run: |
          cd terraform
          terraform apply \
            -input=false \
            -no-color \
            tfplan