name: PR-Job
on:
  pull_request:
    branches:
      - main
jobs:
  PR_Job:
    runs-on: ubuntu-20.04
    steps:
      - name: "Install Go"
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.17.7'

      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Run Test"
        run: go test ./...
        
