name: PR-Job
on:
  pull_request:
    branches:
      - main
jobs:
  PR_Job:
    runs-on: ubuntu-20.04
    steps:
      - name: "Install Go"
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.18'

      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Run Test"
        run: go test ./...

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color



